DROP DATABASE IF EXISTS titan_db;

CREATE DATABASE IF NOT EXISTS titan_db;
USE titan_db;

CREATE TABLE IF NOT EXISTS produtos (
    IDPROD INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME CHAR(40),
    COR  CHAR(20)
);

CREATE TABLE IF NOT EXISTS preco (
    IDPRECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRECO DECIMAL(8,2),
    IDPROD INT
);

ALTER TABLE preco ADD CONSTRAINT FK_PREC_PROD
    FOREIGN KEY(IDPROD) REFERENCES produtos(IDPROD);