DROP DATABASE IF EXISTS titantest_php;

CREATE DATABASE IF NOT EXISTS titantest_php;
USE titantest_php;

CREATE TABLE IF NOT EXISTS produtos (
    IDPROD INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME CHAR(40),
    COR  CHAR(20)
);

CREATE TABLE IF NOT EXISTS preço (
    IDPRECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDPROD INT,
    PRECO DECIMAL(8,2)
);

ALTER TABLE preço ADD CONSTRAINT FK_PREC_PROD
    FOREIGN KEY(IDPROD) REFERENCES produtos(IDPROD);